### ISSUE TITLE
Commit, Discard Changes, Create Image buttons covered title bar

### ISSUE THREAD

**Issue by henrywang** [weldr/welder-web#235]
![screenshot-2018-5-22 blueprint](https://user-images.githubusercontent.com/672230/40345306-3b317c7c-5dcb-11e8-8055-93c6af1c6fe8.png)

**Comment by jgiardino** [comment]
@henrywang Is this screen capture from the context of Cockpit? Since this isn't a stand-alone application, maybe we should remove the navigation. The current version of patternfly doesn't support the layout I'm using on the Edit Blueprint page, but I'm hoping that the next version of patternfly handles this type of layout better. But for now, since it only is visible in Cockpit, then I think it's fine to remove the navigation.

**Comment by jgiardino** [comment]
@henrywang Can you check this issue again now that #301 is merged?

**Comment by henrywang** [comment]
Thanks @jgiardino. I cannot reproduce this issue with new version due to unix socket api. But from the first page (blueprints page) of stand alone application, the navigation got removed. So It can be closed from my perspective.
