### ISSUE TITLE
Composer layout issue on Edge

### ISSUE THREAD

**Issue by henrywang** [weldr/welder-web#394]
The "Commit", "Discard Changes", and "Create Image" buttons should be at right up corner. But it's not rendered on the correct position on Edge. This issue cannot be found on Chrome and Firefox.
![edge_layout_issue](https://user-images.githubusercontent.com/672230/47857003-874d1e80-de23-11e8-840e-e6c80ed16fe9.PNG)

**Comment by andreasn** [comment]
@jgiardino @garrett any idea what's up?

**Comment by andreasn** [comment]
Poked around a bit on Edge and it seems that if I remove the property `display: -ms-grid;` from` .cmpsr-grid_wrapper` in `custom.css` it displays as it should.
I think display: -ms-grid; is a IE11 thing, and since we no longer support IE11, I think we can go with just `display: grid;`
I can cook up a quick PR with a fix.

**Comment by andreasn** [comment]
Browser support for grid: https://caniuse.com/#feat=css-grid
